[package]
name = "async-behavior-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.209", features = ["derive"] }
async-trait = "0.1.82"
thiserror = "1.0.63"
anyhow = "1.0.86"
serde_json = "1.0.128"
